[DeviceInfo]
deviceName=Matteo’s AirPods
hearingAidEnabled=false
magicAccEncKey="@ByteArray(\x4K\x9f\n\xec\x66;\xd2\xa1\xfd\xeb\xe8r\x18\x95\xaf)"
magicAccIRK=@ByteArray(56(\xba\xc5\x88\xa8\x44\x42\x35\xd0\xa3#(\xea\xf9)
model=3
